version: '3'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
        volumes:
            - es_data:/usr/share/elasticsearch/data
        environment:
            # setting the heap size
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200"
        
    logstash:
        image: docker.elastic.co/logstash/logstash-oss:6.6.2
        depends_on:
            - elasticsearch
        ports:
            - "5044:5044"

    kibana:
        image: docker.elastic.co/kibana/kibana:6.6.2
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"

volumes:
  es_data:
    driver: local
